name: Run Test
on: [pull_request]
jobs:
  test-ci:
    name: anchor platform test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: yarn install
      - run: yarn test:anchorplatform:ci
