name: Recovery Signer Integration Test
on: [pull_request]
jobs:
  test-ci:
    name: recovery test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start docker
        run:
          docker-compose -f
          @stellar/typescript-wallet-sdk/test/docker/docker-compose.yml up -d
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn build
      - run: yarn test:recovery:ci
      - name: Print Docker Logs
        if: always() # This ensures that the logs are printed even if the tests fail
        run:
          docker-compose -f
          @stellar/typescript-wallet-sdk/test/docker/docker-compose.yml logs
